RUN_ID: "OPCs_dev_TF"
THREADS: 5
adapters: "adapters.fa"
genome_size_bp: 2730871774
peaks_qvalue: 0.0000000001
binsize: "10"
norm_method: "RPKM"
smooth_length: "300"
extsize: "200"
c_t: 'nanoCT'
chip: 'ChIP'
index_bt2_hg: "/home/mattia/Genomes/hg38/fa/hg38"
target_reads: "5000000"
SAMPLES_JSON: '/home/mattia/OPCs_dev_TF/snakemake/samples_ChIP.json'
